#!/usr/bin/env php
<?php

use Illuminate\Container\Container;
use Symfony\Component\Console\Application;
use UnderScorer\CoreCli\Commands\InstallCommand;
use UnderScorer\CoreCli\Commands\MakeModuleCommand;

$rootDir = __DIR__;

$paths = [
    $rootDir . '/vendor/autoload.php',
    $rootDir . '../../../autoload.php',
];

foreach ( $paths as $path ) {
    if ( file_exists( $path ) ) {
        require $path;
        break;
    }
}

$composerString = file_get_contents( __DIR__ . '/composer.json' );
$composerJson   = json_decode( $composerString, true );

/** @var Container $container */
$container = require $rootDir . '/services.php';

try {
    $app = new Application( 'WPK Core CLI', $composerJson[ 'version' ] );
    $app->add( $container->make( InstallCommand::class ) );
    $app->add( $container->make( MakeModuleCommand::class ) );

    $app->run();
} catch ( Exception $e ) {
    echo "Error occured: {$e->getMessage()}";

    exit( 1 );
}
