version: '3.3'

services:

  wp:
    build: .
    restart: always
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - ./:/var/www/html/wp-content/plugins:rw
      - wp:/var/www/html:rw
      - ./docker/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - .docker/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  wp-cli:
    image: wordpress:cli-php7.3
    depends_on:
      - db
      - wp
    environment:
      - APACHE_RUN_USER="www-data"
      - APACHE_RUN_GROUP="www-data"
    volumes:
      - wp:/var/www/html:rw

volumes:
  wp: {}
